### ISSUE TITLE
Usage of Task.Delay will not work as intended

### ISSUE THREAD

**Issue by kennethito** [jeremylindsayni/Bifrost.IO.Ports#1]
Use of an unawaited Task.Delay creates a separate task which completes after its delay.  It does not sleep the current thread.  There are various usages of Task.Delay across the project which will do nothing.  This is easily verified by changing the delay to -1 (forever), or any other large value and seeing that code still executes past the Task.Delay

Example.
https://github.com/jeremylindsayni/Bifrost.IO.Ports/blob/master/Bifrost.IO.Ports/SerialPort.cs#L57

**Comment by AleksandarDev** [comment]
@kennethito Will `await Task.Delay(delayMs)` and making methods `async` do?

**Comment by kennethito** [comment]
It would, but its heavily emphasized that you shouldn't use async void methods, so it would be a signature change.  Something like, "public async Task Open()"

**Comment by kennethito** [comment]
Stale.
